### ISSUE TITLE
init

### ISSUE THREAD

**Issue by septembersixth** [septembersixth/glory-blog#1]
# Todo list
- [x] import ZF2 skeleton
- [x] Create doctrine entity
- [x] Create controller crud
- [x] Create post dashboard
- [x] Add tag-post relation
- [x] Theme the front page
- [x] upload image
- [x] crud for tag
- [x] add front page post detail'
- [ ] add text editor
- [x] correct menu in front
- [x] correct sidebar
- [x] add input "url" in form admin
- [ ] wrong layout when error routing
- [ ] create phing task
- [x] add comment functionality
- [x] add paginator for front
- [ ] write the readme
- [x] form init with em twice ?
